[2024-10-24T13:09:17.856+0000] {processor.py:186} INFO - Started process (PID=38428) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:09:17.857+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:09:17.858+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:09:17.858+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:09:17.869+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:09:17.868+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:09:17.870+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:09:17.887+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.036 seconds
[2024-10-24T13:09:48.522+0000] {processor.py:186} INFO - Started process (PID=38492) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:09:48.523+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:09:48.524+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:09:48.524+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:09:48.534+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:09:48.533+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:09:48.534+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:09:48.558+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.041 seconds
[2024-10-24T13:10:19.169+0000] {processor.py:186} INFO - Started process (PID=38556) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:10:19.170+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:10:19.171+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:10:19.171+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:10:19.183+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:10:19.182+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:10:19.184+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:10:19.220+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.057 seconds
[2024-10-24T13:10:49.663+0000] {processor.py:186} INFO - Started process (PID=38626) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:10:49.664+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:10:49.665+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:10:49.665+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:10:49.677+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:10:49.676+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:10:49.677+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:10:49.697+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.039 seconds
[2024-10-24T13:11:20.278+0000] {processor.py:186} INFO - Started process (PID=38691) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:11:20.279+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:11:20.280+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:11:20.279+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:11:20.292+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:11:20.291+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:11:20.293+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:11:20.312+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.040 seconds
[2024-10-24T13:11:50.813+0000] {processor.py:186} INFO - Started process (PID=38755) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:11:50.814+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:11:50.815+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:11:50.815+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:11:50.824+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:11:50.823+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:11:50.825+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:11:50.845+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.038 seconds
[2024-10-24T13:12:21.575+0000] {processor.py:186} INFO - Started process (PID=38819) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:12:21.576+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:12:21.578+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:12:21.577+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:12:21.592+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:12:21.591+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:12:21.593+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:12:21.610+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.042 seconds
[2024-10-24T13:12:51.917+0000] {processor.py:186} INFO - Started process (PID=38883) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:12:51.918+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:12:51.919+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:12:51.919+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:12:51.928+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:12:51.928+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:12:51.929+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:12:51.950+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.039 seconds
[2024-10-24T13:13:22.788+0000] {processor.py:186} INFO - Started process (PID=38947) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:13:22.789+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:13:22.790+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:13:22.790+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:13:22.803+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:13:22.802+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:13:22.803+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:13:22.821+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.040 seconds
[2024-10-24T13:13:53.173+0000] {processor.py:186} INFO - Started process (PID=39011) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:13:53.174+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:13:53.175+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:13:53.175+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:13:53.184+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:13:53.183+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:13:53.185+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:13:53.207+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.040 seconds
[2024-10-24T13:14:24.117+0000] {processor.py:186} INFO - Started process (PID=39075) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:14:24.118+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:14:24.119+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:14:24.119+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:14:24.132+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:14:24.131+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:14:24.133+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:14:24.156+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.045 seconds
[2024-10-24T13:14:55.034+0000] {processor.py:186} INFO - Started process (PID=39139) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:14:55.036+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:14:55.037+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:14:55.037+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:14:55.046+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:14:55.045+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:14:55.047+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:14:55.067+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.039 seconds
[2024-10-24T13:15:25.125+0000] {processor.py:186} INFO - Started process (PID=39203) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:15:25.126+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:15:25.127+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:15:25.127+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:15:25.135+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:15:25.135+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:15:25.136+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:15:25.153+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.033 seconds
[2024-10-24T13:15:55.318+0000] {processor.py:186} INFO - Started process (PID=39267) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:15:55.319+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:15:55.321+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:15:55.320+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:15:55.332+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:15:55.331+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:15:55.333+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:15:55.355+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.046 seconds
[2024-10-24T13:16:25.419+0000] {processor.py:186} INFO - Started process (PID=39331) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:16:25.421+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:16:25.422+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:16:25.422+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:16:25.432+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:16:25.430+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:16:25.433+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:16:25.452+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.039 seconds
[2024-10-24T13:16:55.670+0000] {processor.py:186} INFO - Started process (PID=39395) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:16:55.672+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:16:55.673+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:16:55.673+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:16:55.684+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:16:55.683+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:16:55.685+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:16:55.703+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.039 seconds
[2024-10-24T13:17:26.414+0000] {processor.py:186} INFO - Started process (PID=39458) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:17:26.415+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:17:26.416+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:17:26.416+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:17:26.425+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:17:26.424+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:17:26.426+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:17:26.444+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.036 seconds
[2024-10-24T13:17:56.701+0000] {processor.py:186} INFO - Started process (PID=39520) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:17:56.702+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:17:56.703+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:17:56.703+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:17:56.711+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:17:56.710+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:17:56.711+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:17:56.730+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.034 seconds
[2024-10-24T13:18:26.970+0000] {processor.py:186} INFO - Started process (PID=39582) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:18:26.971+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:18:26.972+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:18:26.972+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:18:26.987+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:18:26.986+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:18:26.988+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:18:27.012+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.053 seconds
[2024-10-24T13:18:57.648+0000] {processor.py:186} INFO - Started process (PID=39645) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:18:57.649+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:18:57.650+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:18:57.650+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:18:57.658+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:18:57.658+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:18:57.659+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:18:57.679+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.037 seconds
[2024-10-24T13:19:28.043+0000] {processor.py:186} INFO - Started process (PID=39707) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:19:28.044+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:19:28.045+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:19:28.045+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:19:28.058+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:19:28.057+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:19:28.059+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:19:28.077+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.039 seconds
[2024-10-24T13:19:58.274+0000] {processor.py:186} INFO - Started process (PID=39768) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:19:58.275+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:19:58.277+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:19:58.277+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:19:58.288+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:19:58.287+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:19:58.289+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:19:58.308+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.039 seconds
[2024-10-24T13:20:28.369+0000] {processor.py:186} INFO - Started process (PID=39826) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:20:28.370+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:20:28.373+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:20:28.372+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:20:28.386+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:20:28.385+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:20:28.386+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:20:28.409+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.045 seconds
[2024-10-24T13:20:58.578+0000] {processor.py:186} INFO - Started process (PID=39879) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:20:58.579+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:20:58.580+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:20:58.580+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:20:58.590+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:20:58.589+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:20:58.591+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:20:58.613+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.039 seconds
[2024-10-24T13:21:28.953+0000] {processor.py:186} INFO - Started process (PID=39942) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:21:28.954+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:21:28.955+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:21:28.955+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:21:28.964+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:21:28.963+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:21:28.965+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:21:28.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.035 seconds
[2024-10-24T13:21:59.841+0000] {processor.py:186} INFO - Started process (PID=40006) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:21:59.850+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:21:59.852+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:21:59.851+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:21:59.865+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:21:59.864+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:21:59.866+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:21:59.889+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.055 seconds
[2024-10-24T13:22:30.270+0000] {processor.py:186} INFO - Started process (PID=40070) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:22:30.271+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:22:30.272+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:22:30.271+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:22:30.282+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:22:30.281+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:22:30.283+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:22:30.302+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.037 seconds
[2024-10-24T13:23:00.779+0000] {processor.py:186} INFO - Started process (PID=40134) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:23:00.780+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:23:00.781+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:23:00.781+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:23:00.791+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:23:00.789+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:23:00.791+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:23:00.815+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.041 seconds
[2024-10-24T13:23:31.582+0000] {processor.py:186} INFO - Started process (PID=40198) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:23:31.583+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:23:31.585+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:23:31.585+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:23:31.597+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:23:31.596+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:23:31.598+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:23:31.620+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.044 seconds
[2024-10-24T13:24:02.265+0000] {processor.py:186} INFO - Started process (PID=40262) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:24:02.266+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:24:02.267+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:24:02.267+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:24:02.276+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:24:02.276+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:24:02.277+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:24:02.299+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.039 seconds
[2024-10-24T13:24:32.741+0000] {processor.py:186} INFO - Started process (PID=40327) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:24:32.742+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:24:32.743+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:24:32.743+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:24:32.754+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:24:32.753+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:24:32.754+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:24:32.774+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.040 seconds
[2024-10-24T13:25:03.453+0000] {processor.py:186} INFO - Started process (PID=40391) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:25:03.454+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:25:03.455+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:25:03.455+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:25:03.464+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:25:03.463+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:25:03.465+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:25:03.484+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.037 seconds
[2024-10-24T13:25:34.248+0000] {processor.py:186} INFO - Started process (PID=40455) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:25:34.250+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:25:34.251+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:25:34.251+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:25:34.264+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:25:34.263+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:25:34.265+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:25:34.287+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.046 seconds
[2024-10-24T13:26:04.452+0000] {processor.py:186} INFO - Started process (PID=40519) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:26:04.453+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:26:04.454+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:26:04.454+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:26:04.463+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:26:04.462+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:26:04.464+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:26:04.484+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.038 seconds
[2024-10-24T13:26:34.701+0000] {processor.py:186} INFO - Started process (PID=40583) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:26:34.703+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:26:34.704+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:26:34.704+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:26:34.717+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:26:34.716+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:26:34.718+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:26:34.739+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.046 seconds
[2024-10-24T13:27:04.921+0000] {processor.py:186} INFO - Started process (PID=40647) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:27:04.922+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:27:04.923+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:27:04.923+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:27:04.933+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:27:04.932+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:27:04.934+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:27:04.954+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.037 seconds
[2024-10-24T13:27:35.123+0000] {processor.py:186} INFO - Started process (PID=40711) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:27:35.124+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:27:35.125+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:27:35.125+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:27:35.135+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:27:35.134+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:27:35.135+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:27:35.155+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.038 seconds
[2024-10-24T13:28:05.286+0000] {processor.py:186} INFO - Started process (PID=40775) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:28:05.287+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:28:05.288+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:28:05.288+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:28:05.299+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:28:05.298+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:28:05.299+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:28:05.321+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.041 seconds
[2024-10-24T13:28:36.016+0000] {processor.py:186} INFO - Started process (PID=40839) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:28:36.017+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:28:36.019+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:28:36.019+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:28:36.030+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:28:36.028+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:28:36.030+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:28:36.051+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.042 seconds
[2024-10-24T13:29:06.084+0000] {processor.py:186} INFO - Started process (PID=40903) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:29:06.085+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:29:06.086+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:29:06.086+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:29:06.096+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:29:06.095+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:29:06.097+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:29:06.118+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.039 seconds
[2024-10-24T13:29:36.250+0000] {processor.py:186} INFO - Started process (PID=40967) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:29:36.251+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:29:36.253+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:29:36.252+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:29:36.266+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:29:36.265+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:29:36.266+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:29:36.290+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.046 seconds
[2024-10-24T13:30:06.564+0000] {processor.py:186} INFO - Started process (PID=41031) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:30:06.564+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:30:06.566+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:30:06.565+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:30:06.576+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:30:06.575+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:30:06.577+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:30:06.597+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.039 seconds
[2024-10-24T13:30:36.718+0000] {processor.py:186} INFO - Started process (PID=41095) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:30:36.719+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:30:36.721+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:30:36.720+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:30:36.730+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:30:36.729+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:30:36.731+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:30:36.753+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.040 seconds
[2024-10-24T13:31:07.001+0000] {processor.py:186} INFO - Started process (PID=41159) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:31:07.002+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:31:07.004+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:31:07.003+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:31:07.015+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:31:07.014+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:31:07.015+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:31:07.034+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.040 seconds
[2024-10-24T13:31:37.178+0000] {processor.py:186} INFO - Started process (PID=41223) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:31:37.180+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:31:37.182+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:31:37.182+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:31:37.201+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:31:37.200+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:31:37.202+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:31:37.221+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.048 seconds
[2024-10-24T13:32:07.598+0000] {processor.py:186} INFO - Started process (PID=41287) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:32:07.600+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:32:07.604+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:32:07.603+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:32:07.620+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:32:07.619+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:32:07.621+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:32:07.648+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.060 seconds
[2024-10-24T13:32:37.797+0000] {processor.py:186} INFO - Started process (PID=41351) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:32:37.798+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:32:37.799+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:32:37.799+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:32:37.807+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:32:37.806+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:32:37.807+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:32:37.825+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.033 seconds
[2024-10-24T13:33:07.908+0000] {processor.py:186} INFO - Started process (PID=41415) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:33:07.909+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:33:07.911+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:33:07.910+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:33:07.921+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:33:07.919+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:33:07.922+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:33:07.941+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.039 seconds
[2024-10-24T13:33:38.968+0000] {processor.py:186} INFO - Started process (PID=41479) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:33:38.969+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:33:38.971+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:33:38.971+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:33:38.985+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:33:38.984+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:33:38.986+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:33:39.008+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.046 seconds
[2024-10-24T13:34:09.721+0000] {processor.py:186} INFO - Started process (PID=41543) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:34:09.723+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:34:09.725+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:34:09.724+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:34:09.734+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:34:09.733+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:34:09.734+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:34:09.756+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.040 seconds
[2024-10-24T13:34:40.364+0000] {processor.py:186} INFO - Started process (PID=41607) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:34:40.366+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:34:40.367+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:34:40.367+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:34:40.383+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:34:40.382+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:34:40.384+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:34:40.405+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.048 seconds
[2024-10-24T13:35:10.917+0000] {processor.py:186} INFO - Started process (PID=41672) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:35:10.918+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:35:10.919+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:35:10.919+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:35:10.928+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:35:10.927+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:35:10.928+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:35:10.948+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.037 seconds
[2024-10-24T13:35:41.592+0000] {processor.py:186} INFO - Started process (PID=41736) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:35:41.593+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:35:41.594+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:35:41.594+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:35:41.614+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:35:41.613+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:35:41.615+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:35:41.642+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.059 seconds
[2024-10-24T13:36:12.385+0000] {processor.py:186} INFO - Started process (PID=41801) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:36:12.386+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:36:12.387+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:36:12.386+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:36:12.396+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:36:12.395+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:36:12.396+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:36:12.417+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.037 seconds
[2024-10-24T13:36:43.143+0000] {processor.py:186} INFO - Started process (PID=41865) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:36:43.144+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:36:43.145+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:36:43.145+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:36:43.164+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:36:43.163+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:36:43.165+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:36:43.190+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.052 seconds
[2024-10-24T13:37:13.743+0000] {processor.py:186} INFO - Started process (PID=41929) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:37:13.744+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:37:13.745+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:37:13.745+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:37:13.757+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:37:13.756+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:37:13.757+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:37:13.779+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.041 seconds
[2024-10-24T13:37:44.314+0000] {processor.py:186} INFO - Started process (PID=41993) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:37:44.315+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:37:44.316+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:37:44.316+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:37:44.326+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:37:44.326+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:37:44.327+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:37:44.342+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.033 seconds
[2024-10-24T13:38:14.704+0000] {processor.py:186} INFO - Started process (PID=42057) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:38:14.705+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:38:14.706+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:38:14.706+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:38:14.717+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:38:14.716+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:38:14.717+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:38:14.738+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.040 seconds
[2024-10-24T13:38:45.121+0000] {processor.py:186} INFO - Started process (PID=42121) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:38:45.122+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:38:45.123+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:38:45.123+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:38:45.136+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:38:45.133+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:38:45.137+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:38:45.158+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.044 seconds
[2024-10-24T13:39:15.577+0000] {processor.py:186} INFO - Started process (PID=42185) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:39:15.577+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:39:15.578+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:39:15.578+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:39:15.590+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:39:15.589+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:39:15.591+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:39:15.611+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.039 seconds
[2024-10-24T13:39:46.057+0000] {processor.py:186} INFO - Started process (PID=42249) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:39:46.058+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:39:46.059+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:39:46.059+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:39:46.067+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:39:46.066+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:39:46.067+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:39:46.087+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.035 seconds
[2024-10-24T13:40:16.514+0000] {processor.py:186} INFO - Started process (PID=42313) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:40:16.514+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:40:16.516+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:40:16.515+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:40:16.524+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:40:16.523+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:40:16.525+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:40:16.542+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.033 seconds
[2024-10-24T13:40:47.131+0000] {processor.py:186} INFO - Started process (PID=42377) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:40:47.132+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:40:47.133+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:40:47.133+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:40:47.141+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:40:47.140+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:40:47.141+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:40:47.160+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.034 seconds
[2024-10-24T13:41:17.568+0000] {processor.py:186} INFO - Started process (PID=42441) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:41:17.569+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:41:17.570+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:41:17.570+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:41:17.585+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:41:17.584+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:41:17.586+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:41:17.605+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.042 seconds
[2024-10-24T13:41:48.148+0000] {processor.py:186} INFO - Started process (PID=42505) to work on /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:41:48.149+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/prueba_dag.py for tasks to queue
[2024-10-24T13:41:48.151+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:41:48.150+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:41:48.162+0000] {logging_mixin.py:190} INFO - [2024-10-24T13:41:48.161+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/prueba_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba_dag.py", line 3
    from airflow.operators.empty 
                                 ^
SyntaxError: invalid syntax
[2024-10-24T13:41:48.163+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba_dag.py
[2024-10-24T13:41:48.179+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/prueba_dag.py took 0.038 seconds
